defaults:
  - dataset: folder_dataset
  - loss: cross_entropy
  - model: resnet18
  - optimizer: adam
  - scheduler: onecycle
  - transforms: mytransforms
  - trainer: classification_trainer
  - override hydra/job_logging: disabled