defaults:
  - _self_
  - dataset: folder_dataset
  - loss: bce
  - model: dcgan
  - optimizer: adam
#  - scheduler: onecycle
  - transforms: dcgan_transforms
  - trainer: dcgan_trainer
  - override hydra/sweeper: optuna
  - override hydra/job_logging: disabled


hydra:
  sweeper:
    direction: "maximize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2
