defaults:
  - _self_
  - dataset: folder_dataset
  - loss: cross_entropy
  - model: resnet18
  - optimizer: adam
  - scheduler: onecycle
  - transforms: mnist_transforms
  - trainer: classification_trainer

  - override hydra/job_logging: disabled
  - override hydra/sweeper: optuna



hydra:
  sweeper:
    direction: "maximize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2
