defaults:
  - _self_
  - dataset: folder_dataset
  - miner: triplet_margin_miner
  - loss: triplet_margin_loss
  - model: resnet18_features
  - optimizer: adam
  - scheduler: onecycle
  - transforms: mnist_transforms
  - trainer: metric_learning_trainer

  - override hydra/sweeper: optuna
  - override hydra/job_logging: disabled

hydra:
  sweeper:
    direction: "maximize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2
