defaults:
  - _self_
  - dataset: flood_area_dataset
  - loss: bce_logits
  - model: unet
  - optimizer: adam
  - scheduler: onecycle
  - transforms: mytransforms
  - trainer: segmentation_trainer

  - override hydra/sweeper: optuna
  - override hydra/job_logging: disabled

hydra:
  sweeper:
    direction: "maximize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2