dataset_name: FloodAreaSegmentation
train_path: ../data/flood_area-segmentation/train
val_path: ../data/flood_area-segmentation/test
settings:
  batch_size: 16
  images_path: Image/
  masks_path: Mask/
  train_ratio: 0.7
  labels: ["nowater", "water"]