dataset_name: FolderDataset
validation: True  # indicates if there is a predefined validation set
settings:
  batch_size: 16
  train_path: dataset/MIT_small_train_1/train
  val_path: dataset/MIT_small_train_1/test
  labels: {0: "coast", 1: "forest", 2: "highway", 3: "inside_city", 4: "mountain", 5: "Opencountry", 6: "street", 7: "tallbuilding"}
