# Dataset config
data_path: /media/fran/DATA/miquel/Port-JorfLasfar/Dataset
class_names: [
  'chocho_conc',
  'co_conc',
  'dust',
  'pm10_ss_conc',
  'ecres_conc',
  'ectot_conc',
  'hcho_conc',
  'nh3_conc',
  'nmvoc_conc',
  'no2_conc',
  'no_conc',
  'o3_conc',
  'pans_conc',
  'pm10_conc',
  'pm2p5_total_om_conc',
  'pm2p5_conc',
  'pmwf_conc',
  'sia_conc',
  'so2_conc'
]
cams: ['Jetee']

# Early stopping config
patience: 10
min_delta: 0.0
max_mode: False
monitor: loss

# Model config
n_classes: 19

# Trainer config
batch_size: 32
n_epochs: 1
device: cuda
wandb: null

# Optimizer config
lr: 0.001
max_lr: 0.01


defaults:
  - _self_
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    direction: "minimize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2