# Dataset config
data_path: /media/fran/DATA/miquel/Pytorch-training-toolkit/data/Clothes
labels: [
    "null",
    "accessories",
    "bag",
    "belt",
    "blazer",
    "blouse",
    "bodysuit",
    "boots",
    "bra",
    "bracelet",
    "cape",
    "cardigan",
    "clogs",
    "coat",
    "dress",
    "earrings",
    "flats",
    "glasses",
    "gloves",
    "hair",
    "hat",
    "heels",
    "hoodie",
    "intimate",
    "jacket",
    "jeans",
    "jumper",
    "leggings",
    "loafers",
    "necklace",
    "panties",
    "pants",
    "pumps",
    "purse",
    "ring",
    "romper",
    "sandals",
    "scarf",
    "shirt",
    "shoes",
    "shorts",
    "skin",
    "skirt",
    "sneakers",
    "socks",
    "stockings",
    "suit",
    "sunglasses",
    "sweater",
    "sweatshirt",
    "swimwear",
    "t-shirt",
    "tie",
    "tights",
    "top",
    "vest",
    "wallet",
    "watch",
    "wedges"
]


# Early stopping config
patience: 10000
min_delta: 0.0
max_mode: False
monitor: loss

# Model config
n_classes: 59

# Trainer config
batch_size: 16
n_epochs: 3
device: cuda
wandb: null

# Optimizer config
lr: 0.0001
max_lr: 0.01