# Dataset config
data_path: /media/fran/DATA/miquel/Pytorch-training-toolkit/data/Flood
labels: [
    "nowater",
    "water"
]

# Early stopping config
patience: 10000
min_delta: 0.0
max_mode: False
monitor: loss

# Model config
n_classes: 1

# Trainer config
batch_size: 16
n_epochs: 1
device: cuda
wandb: null

# Optimizer config
lr: 0.001
max_lr: 0.01