# Dataset config
data_path: /media/fran/DATA/miquel/Pytorch-training-toolkit/data/MNIST
labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

# Early stopping config
patience: 10000
min_delta: 0.0
max_mode: False
monitor: loss

# Model config
n_classes: 10

# Trainer config
batch_size: 64
n_epochs: 3
device: cuda
wandb: null

# Optimizer config
lr: 0.0001
max_lr: 0.01


defaults:
  - _self_
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    direction: "minimize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2