# Dataset config
data_path: ../../data/UCF101

# Model config
n_frames: 10
n_classes: 5
model_name: resnet50

# Early stopping config
patience: 10000
min_delta: 0.0
max_mode: False
monitor: loss

# Trainer config
batch_size: 1
n_epochs: 10
device: cuda
wandb: null
loss_computed_by_model: False

# Optimizer config
lr: 0.001
max_lr: 0.01


#defaults:
#  - _self_
#  - override hydra/sweeper: optuna
#
#hydra:
#  sweeper:
#    direction: "minimize"
#    study_name: null
#    storage: null
#    n_trials: 20
#    n_jobs: 2





