data_path: /home/miquel/Desktop/Workspace/Pytorch-training-toolkit/data/UCF101
batch_size: 3
n_epochs: 10
lr: 1e-3
n_frames: 10
n_classes: 5


defaults:
  - _self_
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    direction: "minimize"
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 2